steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'us-central1-docker.pkg.dev/my-first-project1/gke-repo/quickstart-image', './app1']
    id: 'Build Docker Image'

  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'us-central1-docker.pkg.dev/my-first-project1/gke-repo/quickstart-image']
    id: 'Push Docker Image'

  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'us-central1-docker.pkg.dev/my-first-project1/gke-repo/quickstart-image', './app2']
    id: 'Build Docker Image2'
